# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:lts
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Download and cache node-cache
      - restore_cache:
          keys:
          - v1-nodecache-{{ checksum "gulpfile.js" }}
          # fallback to using the latest cache if no exact match is found
          - v1-nodecache-

      - run: npm prune    
      - run: npm install
      #- run: sudo npm install -g gulp 
        
      # run tests!
      #- run: gulp build linux32,linux64,win32,win64,osx64
      - run: npx gulp build -p linux32,linux64,win32,win64
      
      - deploy:
         command: npx gulp zip -p linux32,linux64,win32,win64
      
      #store cache dependencies
      - save_cache:
         key: v1-dependencies-{{ checksum "package-lock.json" }}
         paths:
            - node_modules

      #store node cache
      - save_cache:
         key: v1-nodecache-{{ checksum "gulpfile.js" }}
         paths:
            - cache
      
      - store_artifacts:
         path: ~/repo/dist

